name: Build pdf
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Compile
        uses: xu-cheng/latex-action@master
        with:
          root_file: main.tex
          args: "-shell-escape"
      - name: upload
        uses: actions/upload-artifact@v4
        if: success()
        with:
          name: main
          path: ./main.pdf
